title: Gloria Lee
email: glorialee1@yahoo.com
description: Web Developer
baseurl: "http://gloria-lee.com"
url: "http://gloria-lee.com"
github_username:  gmgl21
markdown: kramdown
author: Gloria Lee
authorurl: http://www.gloria-lee.com
exclude: ["node_modules", "gulpfile.js", "package.json"]
